-- Atshri: full public site content (menu, categories, activities, team, stats, values)
-- Target: PostgreSQL / Supabase (and compatible clients)
-- Regenerate: python scripts/generate_seed_sql.py

BEGIN;

-- Clear existing content rows (keeps contacts / volunteers if any)
TRUNCATE TABLE
  activities,
  categories,
  menu_items,
  team_members,
  stats,
  values
RESTART IDENTITY CASCADE;

INSERT INTO menu_items (id, icon, label_en, label_hi, visible, page_enabled, show_in_nav, sort_order) VALUES ('home', '🏠', 'Home', 'होम', TRUE, TRUE, TRUE, 1);
INSERT INTO menu_items (id, icon, label_en, label_hi, visible, page_enabled, show_in_nav, sort_order) VALUES ('about', 'ℹ️', 'About Us', 'हमारे बारे में', TRUE, TRUE, TRUE, 2);
INSERT INTO menu_items (id, icon, label_en, label_hi, visible, page_enabled, show_in_nav, sort_order) VALUES ('activities', '🎯', 'Activities', 'गतिविधियाँ', TRUE, TRUE, TRUE, 3);
INSERT INTO menu_items (id, icon, label_en, label_hi, visible, page_enabled, show_in_nav, sort_order) VALUES ('gallery', '🖼️', 'Gallery', 'गैलरी', TRUE, TRUE, TRUE, 4);
INSERT INTO menu_items (id, icon, label_en, label_hi, visible, page_enabled, show_in_nav, sort_order) VALUES ('involved', '🤝', 'Get Involved', 'जुड़ें', FALSE, FALSE, FALSE, 5);
INSERT INTO menu_items (id, icon, label_en, label_hi, visible, page_enabled, show_in_nav, sort_order) VALUES ('contact', '📞', 'Contact', 'संपर्क', FALSE, FALSE, FALSE, 6);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('water', '💧', 'Water Service', 'जल सेवा', '#2563EB', TRUE, 1);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('blanket', '🧣', 'Blanket Drive', 'कम्बल वितरण', '#7C3AED', TRUE, 2);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('temple', '🛕', 'Temple Seva', 'मंदिर सेवा', '#EA580C', TRUE, 3);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('food', '🍱', 'Food Distribution', 'अन्न सेवा', '#16A34A', TRUE, 4);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('tree', '🌳', 'Tree Plantation', 'वृक्षारोपण', '#15803D', TRUE, 5);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('blood', '🩸', 'Blood Donation', 'रक्तदान', '#DC2626', TRUE, 6);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('education', '📚', 'Education Support', 'शिक्षा सहयोग', '#4F46E5', TRUE, 7);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('elderly', '👴', 'Elderly Care', 'वृद्ध सेवा', '#D97706', TRUE, 8);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('clean', '🧹', 'Cleanliness Drive', 'स्वच्छता अभियान', '#0D9488', TRUE, 9);
INSERT INTO categories (id, icon, name_en, name_hi, color, visible, sort_order) VALUES ('relief', '🆘', 'Disaster Relief', 'आपदा राहत', '#B91C1C', TRUE, 10);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (1, '💧', 'water', 'Summer Water Distribution', 'ग्रीष्म जल वितरण', '2024-05-20'::date, 'Distributed free water and chilled sherbat to over 500 people during peak summer heat in Rewa. Volunteers set up 8 stalls across the city.', 'भोपाल में गर्मी के चरम पर 500 से अधिक लोगों को निःशुल्क पानी और शरबत वितरित किया। स्वयंसेवकों ने शहर भर में 8 स्टॉल लगाए।', '', FALSE, FALSE, FALSE, 1);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (2, '🧣', 'blanket', 'Winter Blanket Distribution', 'शीत कम्बल वितरण', '2023-12-15'::date, 'Distributed 200 warm blankets to homeless individuals and underprivileged families during freezing winter nights in Rewa.', 'भोपाल में कड़कड़ाती सर्दियों में बेघर लोगों और जरूरतमंद परिवारों को 200 गर्म कम्बल वितरित किए।', '', FALSE, FALSE, FALSE, 2);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (3, '🛕', 'temple', 'Mandir Cleaning & Seva', 'मंदिर सफाई एवं सेवा', '2024-01-14'::date, 'Organised a full-day mandir cleaning, flower decoration, and community aarti at 5 local temples. Over 60 volunteers participated.', '5 स्थानीय मंदिरों में पूरे दिन की सफाई, फूलों की सजावट और सामूहिक आरती का आयोजन किया। 60 से अधिक स्वयंसेवकों ने भाग लिया।', '', FALSE, FALSE, FALSE, 3);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (4, '🍱', 'food', 'Community Bhandara', 'सामुदायिक भंडारा', '2024-03-08'::date, 'Served hot, nutritious meals to 1,000+ people in a grand Bhandara organised for underprivileged communities on Holi.', 'होली पर वंचित समुदायों के लिए आयोजित महाभंडारे में 1,000+ लोगों को गर्म पौष्टिक भोजन परोसा।', '', FALSE, FALSE, FALSE, 4);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (5, '🌳', 'tree', 'Tree Plantation Drive', 'वृक्षारोपण अभियान', '2024-06-05'::date, 'Planted 150 saplings across Rewa neighbourhoods on World Environment Day to promote a greener, healthier city.', 'विश्व पर्यावरण दिवस पर भोपाल के विभिन्न क्षेत्रों में 150 पौधे लगाए।', '', FALSE, FALSE, FALSE, 5);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (6, '🩸', 'blood', 'Blood Donation Camp', 'रक्तदान शिविर', '2024-04-14'::date, 'Organised a blood donation camp in collaboration with a local hospital. 75 volunteers donated blood for critically ill patients.', 'स्थानीय अस्पताल के सहयोग से रक्तदान शिविर आयोजित किया। 75 स्वयंसेवकों ने गंभीर रोगियों के लिए रक्तदान किया।', '', FALSE, FALSE, FALSE, 6);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (7, '📚', 'education', 'Stationery Distribution', 'स्टेशनरी वितरण', '2024-07-10'::date, 'Distributed notebooks, pens, and school bags to 120 children from low-income families at the start of the new academic session.', 'नए शैक्षणिक सत्र की शुरुआत में कम आय वाले परिवारों के 120 बच्चों को नोटबुक, पेन और स्कूल बैग वितरित किए।', '', FALSE, FALSE, FALSE, 7);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (8, '🧹', 'clean', 'Swachh Rewa Drive', 'स्वच्छ भोपाल अभियान', '2024-10-02'::date, 'On Gandhi Jayanti, 80 volunteers cleaned 3 km of the main road and a local park as part of the Swachh Bharat Abhiyan.', 'गांधी जयंती पर 80 स्वयंसेवकों ने स्वच्छ भारत अभियान के तहत मुख्य सड़क और एक पार्क की 3 किमी सफाई की।', '', FALSE, FALSE, FALSE, 8);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (9, '💧', 'water', 'Summer Relief 2026 — Water Stalls', 'ग्रीष्म राहत 2026 — जल स्टॉल', '2026-04-29'::date, 'We are going to open drinking-water and sharbat stalls across Rewa as the heat rises. You can help: volunteer a few hours, sponsor one stall, or donate bottles and ingredients. Tell neighbours and share the date — every hand makes the seva warmer.', 'गर्मी बढ़ते ही हम रीवा भर में पानी और शरबत के स्टॉल लगाएंगे। आप भी जुड़ सकते हैं: कुछ घंटे सेवा करें, एक स्टॉल प्रायोजित करें, या बोतल व सामग्री दान करें। तारीख परिवार-पड़ोस में बताएं — हर हाथ सेवा को और सार्थक बनाता है।', '', TRUE, FALSE, TRUE, 9);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (10, '📚', 'education', 'Back-to-School Kits 2026', 'स्कूल किट वितरण 2026', '2026-06-20'::date, 'We will pack and give school bags, notebooks, and pens to 200+ children before the new term. Join us on packing day, donate kits, or help us reach families — message us if your school or colony wants to partner.', 'नए सत्र से पहले 200+ बच्चों को बैग, नोटबुक और कलम देंगे। पैकिंग दिन पर आएं, किट दान करें, या परिवारों तक पहुँचने में मदद करें — अगर आपका स्कूल या मोहल्ला साथ आना चाहे तो लिखें।', '', TRUE, FALSE, TRUE, 10);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (11, '🩸', 'blood', 'Monsoon Blood Donation Camp', 'मानसून रक्तदान शिविर', '2026-07-12'::date, 'On camp day we will welcome donors with the district hospital team — walk in or register early, bring a friend, and spread the word in your office or society. One donation can support up to three patients; light breakfast will be served for donors.', 'शिविर के दिन जिला अस्पताल की टीम के साथ रक्तदाताओं का स्वागत करेंगे — सीधे आएं या पहले पंजीकरण कराएं, किसी को साथ लाएं, ऑफिस या सोसाइटी में सूचना फैलाएं। एक यूनिट कई रोगियों की मदद कर सकता है; दाताओं के लिए हल्का नाश्ता रहेगा।', '', FALSE, FALSE, FALSE, 11);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (12, '🍱', 'food', 'Next Community Bhandara — Rewa', 'अगला सामुदायिक भंडारा — रीवा', '2026-08-30'::date, 'We are planning a hot-meal Bhandara for 1,000+ neighbours. We will need cooks, servers, donors for groceries, and help with setup from early morning. If you can sponsor a pot of dal or chapatis, or join the serving line, reach out — seva tastes best when we cook it together.', '1,000+ पड़ोसियों के लिए गर्म भोजन भंडारा करने की योजना है। हमें रसोइए, परोसने वाले, राशन दाता और सुबह जल्दी लगाने वाले चाहिए। दाल या रोटी का एक बर्तन दान करें या परोसने की कतार में आएं — साथ मिलकर बनाई सेवा सबसे मीठी लगती है।', '', TRUE, FALSE, FALSE, 12);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (13, '🌳', 'tree', 'Green Rewa — Sapling Drive 2026', 'हरा रीवा — पौधारोपण 2026', '2026-09-05'::date, 'We will plant hundreds of native saplings with students and residents. Bring your family, wear comfortable clothes, and we will share tools and water on site. Sponsors can fund saplings and guards — together we will shade the streets we walk every day.', 'छात्रों और निवासियों के साथ सैकड़ों देशी पौधे लगाएंगे। परिवार साथ लाएं, हल्के कपड़े पहनें — औजार और पानी हम मौके पर देंगे। पौधे और सुरक्षा कवच दान कर सकते हैं — मिलकर उन्हीं सड़कों को छाया देंगे जिन पर हम चलते हैं।', '', TRUE, FALSE, TRUE, 13);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (14, '🩸', 'blood', 'Follow-up Blood Camp (Q4)', 'दोहरा रक्तदान शिविर (अंतिम तिमाही)', '2026-11-08'::date, 'We will run a second camp for those who missed the monsoon drive. First-time donors are especially welcome — our volunteers will guide you through registration and rest. Share this with your building group chat; we will publish the venue two weeks before.', 'मानसून शिविर में जो न आ सके उनके लिए दूसरा शिविर। पहली बार दान करने वालों का विशेष स्वागत — स्वयंसेवक पंजीकरण और आराम में मदद करेंगे। अपनी सोसाइटी ग्रुप में भेजें; दो सप्ताह पहले स्थान घोषित करेंगे।', '', FALSE, FALSE, FALSE, 14);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (15, '📚', 'education', 'Winter Warmth & Stationery Week', 'सर्दी में गर्मजोशी व स्टेशनरी सप्ताह', '2026-11-25'::date, 'We will distribute warm layers plus notebooks to children before winter exams. Donate woollens in good condition, pack pens with your children, or volunteer to sort and label bags. We will post drop-off points — follow for dates and maps.', 'सर्दी की परीक्षाओं से पहले बच्चों को गर्म कपड़े और कॉपी-कलम देंगे। अच्छी ऊनी दान करें, बच्चों से पेन पैक कराएं, या बैग छाँटने में मदद करें। ड्रॉप पॉइंट बताएंगे — तारीख और नक्शे के लिए बने रहें।', '', TRUE, FALSE, FALSE, 15);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (16, '🧹', 'clean', 'Gandhi Jayanti Clean-up 2026', 'गांधी जयंती सफाई 2026', '2026-10-02'::date, 'On 2 October we will clean a main road stretch and a neighbourhood park again. We will start at dawn with gloves and bags provided — bring water and friends. Local shops can sponsor refreshments; we will thank every team loudly at closing circle.', '2 अक्टूबर को फिर मुख्य सड़क और पार्क की सफाई करेंगे। भोर में दस्ताने और थैले देंगे — पानी और दोस्त साथ लाएं। दुकानें चाय-नाश्ता दान कर सकती हैं; अंत में हर टीम का जोर से आभार करेंगे।', '', TRUE, FALSE, TRUE, 16);
INSERT INTO activities (id, icon, category, heading_en, heading_hi, date, text_en, text_hi, image, visible, featured, upcoming, sort_order) VALUES (17, '🧣', 'blanket', 'Winter Blanket Distribution 2026', 'शीत कम्बल वितरण 2026', '2026-12-14'::date, 'When nights turn cold in December, we will hand out warm blankets across Rewa to families who need them most. Help us collect or carry blankets, join a distribution shift, or sponsor bundles — every blanket is a hug of seva.', 'दिसंबर में जब रातें ठंडी होंगी, हम रीवा में जरूरतमंद परिवारों को गर्म कम्बल देंगे। कम्बल इकट्ठा करने, वितरण में शिफ्ट लेने, या बंडल प्रायोजित करने में सहयोग करें — हर कम्बल सेवा का आलिंगन है।', '', TRUE, FALSE, TRUE, 17);
INSERT INTO team_members (id, name, initials, role_en, role_hi, badge, desc_en, desc_hi, visible, sort_order) VALUES (1, 'Maya Manoj Shrivastava', 'MMS', 'Trustee', 'ट्रस्टी', '🌟', 'Founder and driving force behind Atshri''s mission of selfless community service.', 'अतश्री के निःस्वार्थ सेवा मिशन की संस्थापक और प्रेरणाशक्ति।', TRUE, 1);
INSERT INTO team_members (id, name, initials, role_en, role_hi, badge, desc_en, desc_hi, visible, sort_order) VALUES (2, 'Pavan Shrivastava', 'PS', 'Core Member', 'मुख्य सदस्य', '⚙️', 'Leads ground operations and coordinates volunteers for all major activities.', 'स्वयंसेवकों के समन्वय और गतिविधियों के क्रियान्वयन में अग्रणी।', TRUE, 2);
INSERT INTO team_members (id, name, initials, role_en, role_hi, badge, desc_en, desc_hi, visible, sort_order) VALUES (3, 'Abhishek Shrivastav', 'AS', 'Core Member', 'मुख्य सदस्य', '🤝', 'Manages community outreach and connects the trust with people who need support.', 'सामुदायिक आउटरीच और जरूरतमंदों से संपर्क में मुख्य भूमिका।', TRUE, 3);
INSERT INTO stats (id, icon, value, label_en, label_hi, visible, sort_order) VALUES (1, '🎯', '0+', 'Activities Done', 'गतिविधियाँ', TRUE, 1);
INSERT INTO stats (id, icon, value, label_en, label_hi, visible, sort_order) VALUES (2, '🙌', '4+', 'Volunteers', 'स्वयंसेवक', TRUE, 2);
INSERT INTO stats (id, icon, value, label_en, label_hi, visible, sort_order) VALUES (3, '🏠', '0+', 'Families Helped', 'परिवार', TRUE, 3);
INSERT INTO stats (id, icon, value, label_en, label_hi, visible, sort_order) VALUES (4, '⭐', '0+', 'Years of Service', 'वर्ष की सेवा', TRUE, 4);
INSERT INTO values (id, icon, title_en, title_hi, desc_en, desc_hi, visible, sort_order) VALUES (1, '🙏', 'Selfless Service', 'निःस्वार्थ सेवा', 'We serve without expectation of return — pure, unconditional seva.', 'हम बिना किसी अपेक्षा के सेवा करते हैं।', TRUE, 1);
INSERT INTO values (id, icon, title_en, title_hi, desc_en, desc_hi, visible, sort_order) VALUES (2, '🤝', 'Community First', 'समाज प्रथम', 'Every decision is taken for the good of the community, always.', 'हर निर्णय समाज की भलाई के लिए।', TRUE, 2);
INSERT INTO values (id, icon, title_en, title_hi, desc_en, desc_hi, visible, sort_order) VALUES (3, '💡', 'Transparency', 'पारदर्शिता', 'We are fully open and honest about our work and finances.', 'हम अपने काम और वित्त में पूरी तरह ईमानदार हैं।', TRUE, 3);
INSERT INTO values (id, icon, title_en, title_hi, desc_en, desc_hi, visible, sort_order) VALUES (4, '🌍', 'Inclusiveness', 'समावेशिता', 'We serve all — regardless of caste, creed, or religion.', 'हम जाति, पंथ या धर्म की परवाह किए बिना सभी की सेवा करते हैं।', TRUE, 4);

COMMIT;
